project: 
  name : "Howto API"
  author: "Ivan Levin"

grpc:
  address: ":82"

database :
  driver : "postgres"
  port : "5432"
  user : ""
  password : ""
  database : ""
  sslmode : "disable"
  batch_size : 1000

metrics :
  address : ":9100"
  pattern : "/metrics"

kafka:
  events_queue_capacity: 100
  topic : "howto"
  key : "key"
  partition : 0
  brokers:
  - ":9092"
